### PR TITLE
Starting MOS 6502 target.

### PR DESCRIPTION
**Pull request by lambdafu**
Obviously, this should not be merged yet.  This is just a placeholder ticket for now to make the branch more visible.

### CODE REVIEW

**Comment by lambdafu** [comment]
I have a problem: On a dummy test file with hex content ea90ea90ea90 I would expect panopticon to show the instructions "nop unk nop unk nop unk nop unk" but instead I see nothing.  Maybe panopticon only shows fully parsed subroutines or other chunks and does not do anything with top-scope instructions that don't lead to anything?

**Comment by lambdafu** [comment]
Ok, the ins show up in the control flow tab after clicking on the entry point (int).

**Comment by flanfly** [comment]
Yes, you need to select the CFG tab and click the function you want before anything shows up. For development it helps to uncomment the println! in lib/src/function.rs:262. This will dump all recognized opcodes into console.

**Comment by lambdafu** [comment]
The branch now has decoding support for all legal opcodes.  I understand better now what's going on and the code needs to be simplified to be more like the avr target than the intel target (using bit patterns and inline decoding).  Panopticon is fun!

**Comment by lambdafu** [comment]
The MOS-6502 loader allows quick loading of binary images.  The illegal opcodes finish the decoder.  This could be a good merge point.  However, I will also add some semantics soon.

**Comment by lambdafu** [comment]
mos6502

**Comment by lambdafu** [comment]
can be merged now, semantics can be done in another pull request.

**Comment by flanfly** [comment]
Thanks!

**Pull request merged**
