### PR TITLE
Adds basic PLT resolution for mach and elf binaries

### PR DESCRIPTION
**Pull request by m4b**
Adds new PLT resolution scheme for mach and elf binaries.

1. Adds a function::FunctionKind (~~I think we'll want to reexport as FunctionKind perhaps~~);
2. Adds new methods on program and function to rewrite matching function names that are plt stubs to their appropriate type and name

Also:

1. `--reverse-deps` flag for printing every function that calls the given function -f
2. better coloring
3. `--il` to dump rreil (in color, along with the mnemonic it implements, good for surveying what needs to be implemented)
4. fix a bug omitting some actual ELF functions in the plt
5. add mutable function iterator

### CODE REVIEW

**Comment by m4b** [comment]
Some obligatory screenshots:

il dump

screenshot from 2017-08-14 22-58-01

reverse deps

screenshot from 2017-08-14 23-02-01

panic in libc ;)

```
m4b@efrit ::  [ ~/projects/panopticon/cli ] panop /usr/lib/libc.so.6 --reverse-deps -f printf
thread 'main' panicked at '__memcpy_chk_ssse3_back has a call address 0x7fac3ea, but there isn't a function with that address in the program object', /checkout/src/libcore/option.rs:823:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by flanfly** [comment]
@m4b does it again! ❇️ 🥇

**Comment by flanfly** [comment]
btw, it didn't panic when running it against my libc 😕

**Comment by m4b** [comment]
I should have clarified, the panic is because the reverse deps check makes sure that any function in the call addresses is also a resolved function in the program object. 

This is a good assertion imho, but if we don't want to panic can just skip and warn for that call address. 

The function could be missing if for example it couldn't disassemble it because it encountered and error or some fancy instruction, etc. 

I'll test some more to see which function it is, should be deterministic since the call address is checkable in gdb, etc. 

@flanfly while you're here, could you help to implement `leaq` in RREIL? I've been investigating it but it would be great if you could give a pointer, or knew what to do

**Pull request merged**
