### PR TITLE
Pe support

### PR DESCRIPTION
**Pull request by m4b**
### Task List Before acceptable merge can be considered

- [x] remove goblin git in `Cargo.toml`
- [x] merge goblin pe branch into master in goblin
- [x] publish scroll 0.2.0 library on crates (used by goblin)
- [x] publish goblin 0.0.7 on crates
- [x] finish Export data and Import data for PE
- [x] ~~add "unified" interface for PE binary, similar to ELF functionality~~
- [x] add export name for functions in disassembly window
- [x] test 
- [x] ~~determine whether `?` operator is allowed/not allowed in project style (i don't care what ultimately is chosen, but should be consistent for future commits)~~
- [x] use rust 1.15 (2017-02-02) (I know this isn't even released yet, but goblin uses proc macros from [scroll_derive](https://github.com/m4b/scroll_derive) to auto-generate tons of extremely tedious c struct Read/Write implementations (this cuts down on maintenance, initial implementation time, and also simple copy-paste errors I've encountered several times already in struct readers :disappointed:  )
- [x] update readme, docs, buildbots, etc., to use new rust 1.15

### Features

This PR scaffolds initial PE support.

1. adds initial PE support (only 32-bit for now, will add similar "unified" interface to `goblin::pe::PE` to make 32/64 bit binaries transparent to user, like the elf module does). Note, there are definitely some binaries which do not run, need to debug, this is very much in early stages. ~~Double note: we will be able to show exported symbol names in disassembly and in viewer quite easily once that part of goblin is finished; similarly with import names :)~~
1. Displays and disassembles exports from DLLs
1. unifies the ELF and PE loader into a new `loader` module, which `create_project` calls uniformly on the binary
2. match logic in qt file choose etc., is simplified using new `goblin::peek` which returns a variant of `Hint` for the various binary formats goblin understands
3. file picker popup now displays archive (and eventually mach-o when fat/regular mach-o binary better expressed)
4. adds a `From` impl for goblin errors so everything can be used transparently

Obligaatory screenshot running panopticon on `msvcrt.dll` with exported symbols being recognized:

screenshot from 2017-01-24 22-04-03

### CODE REVIEW

**Comment by m4b** [comment]
@flanfly I can only get disassembly and functions to start being resolved when I set `RUST_LOG=debug` before running; hopefully this resolves itself, but its pretty strange...

**Comment by m4b** [comment]
@flanfly I think this is basically ready to go; unfortunately I just don't have time right to add unified pe64 support, let alone test (I don't have any 64-bit PE binaries on hand, and also haven't encountered very many 64-bit container format binaries for windows, so I don't think its as pressing/common as elf)

When I do get it finished, I don't think there will be any real api difference, similar to the `Elf` struct, may have to access elements of the fields via `()` instead of regular field access.

As for testing, there are some issues w.r.t. PE binary analysis itself, more missing instructions, strange sequences etc. seems that panopticon has a harder time reading PE functions than ELF? not sure, but I think this is a good start for now, to mess around with PE, hone the backend, etc.

Let me know any comments or concerns

**Comment by flanfly** [comment]
Amazing work @m4b! The patch looks great. Please add yourself to the authors array on `Cargo.toml`. I'm currently at FOSDEM and I'll merge the PR when I'm back.

**Comment by flanfly** [comment]
Thanks again!

**Pull request merged**
