### PR TITLE
Added qmlc files to gitignore

### PR DESCRIPTION
**Pull request by sphinxc0re**

### CODE REVIEW

**Comment by flanfly** [comment]
What's qmlc :confused::question:

**Comment by sphinxc0re** [comment]
I don't know. But starting panopticon seems to generate these files occasionally

**Comment by sphinxc0re** [comment]
It seems like they are cache files from the JavaScript runtime

**Comment by flanfly** [comment]
Ah!
https://doc.qt.io/qt-5/whatsnew58.html

>What's New in Qt 5.8
> [...]
> Implemented caching of code and data structures generated from .qml and .js files to disk, reducing start-up time and memory consumption. The resulting .qmlc and .jsc cache files are memory mapped.


Fancy.

**Comment by sphinxc0re** [comment]
should we get rid of .jsc files as well then?

**Comment by flanfly** [comment]
I say yes. I wonder where they write these things when you install Panopticon into `/usr/bin`.

**Pull request merged**
