### PR TITLE
Reorganize project & formatting

### LINKED ISSUE #258: split the project into multiple crates
Split the project into sub crates using `{ path = "<blah>" }`.Initially, we only want:
 - panopticon-core (ex libpanopticon)
 - panopticon-qt (ex qtpanopticon)

### PR DESCRIPTION
**Pull request by flanfly**
- splits the project into multiple crates.
- formats everything w/ rustfmt
- integrates graph-algos
- remove old docs
- replace rreil_macro.sh w/ build.rsa
- refactor glue code

fixes #258

### CODE REVIEW

**Comment by flanfly** [comment]
It's a dirty job but somebody has to do it.

**Comment by m4b** [comment]
How come abstract interpretation is its own crate ?

**Comment by flanfly** [comment]
Well, in theory you don't need it. For example disassembling an AVR dump only needs core & avr.

**Comment by m4b** [comment]
Ah k. So lib/src is gone now right ? That always bothered me :)

**Comment by flanfly** [comment]
Yes, most of the lib is now in core.

**Comment by m4b** [comment]
Sweet! I just meant the extra directory of lib, then src

**Comment by flanfly** [comment]
In case there aren't any objections I'll pull the trigger tomorrow.

**Comment by m4b** [comment]
one side of effect of this is compile time will drop when hacking on a submodule :+1:

**Comment by flanfly** [comment]
Yay another 27k loc PR!

**Pull request merged**
